#!/bin/sh
gem_install_or_update() {
  if gem list "$1" --installed > /dev/null; then
    echo "Updating $1 ..."
    gem update "$@"
  else
    echo "Installing $1 ..."
    gem install "$@"
    rbenv rehash
  fi
}

export -f gem_install_or_update
