#!/bin/sh
include_module() {
  set -e

  export MODULE_NAME=$(basename "$1")
  export MODULE_PATH="$1"

  case $2 in
      ''|*[!0-9]*) MODULE_ENV_PRIORITY=20 ;;
      *) MODULE_ENV_PRIORITY=$2 ;;
  esac
  export MODULE_ENV_PRIORITY

  cd "$TILLAGE_REPO"

  if [ -d "$MODULE_PATH" ]; then
    echo "--> Installing $MODULE_NAME module:"

    MODULE_BREWFILE_PATH="$MODULE_PATH/Brewfile"
    MODULE_SCRIPT_PATH="$MODULE_PATH/$MODULE_NAME.sh"

    # Add enviroment script to env.d
    for ext in "sh" "fish"; do
      if [ -f "$MODULE_PATH/templates/env.$ext" ]; then
        if [ -f $TILLAGE_ENV_PATH/*$MODULE_NAME.$ext ]; then
          rm -f $TILLAGE_ENV_PATH/*$MODULE_NAME.$ext
        fi
        render "$MODULE_PATH/templates/env.$ext" > "$TILLAGE_ENV_PATH/$MODULE_ENV_PRIORITY-$MODULE_NAME.$ext"
      fi
    done

    # Install Modules Brewfile
    if [ -f "$MODULE_BREWFILE_PATH" ]; then
      brew bundle --file="$MODULE_BREWFILE_PATH"
    fi

    # Run module script
    echo $MODULE_SCRIPT_PATH
    if [ -f "$MODULE_SCRIPT_PATH" ]; then
      #shellcheck disable=1090
      sh "$MODULE_SCRIPT_PATH"
    fi

    echo "ok"
  else
    echo "$1 not found"
  fi
}

export -f include_module
