#!/bin/sh
npm_install_or_update() {
  if npm list --global --depth=0 --silent "$1" > /dev/null; then
    echo "Updating $1 ..."
  else
    echo "Installing $1 ..."
  fi
  npm install --global "$@"
}

export -f npm_install_or_update
