#!/bin/sh
npm_install_or_update() {
  if npm list --global --depth=0 --silent "$1" > /dev/null; then
    echo "Updating $1 ..."
    npm upgrade --global "$@"
  else
    echo "Installing $1 ..."
    npm install --global "$@"
    nodenv rehash
  fi
}

export -f npm_install_or_update
