# Force OS X.
language: objective-c
os: osx
env: OSX=10.11
osx_image: osx10.11
rvm: 2.1.7
matrix:
  include:
    - env: OSX=10.10
      osx_image: xcode7
    - env: OSX=10.9
      osx_image: beta-xcode6.2

install:
  - ./script/bootstrap

# Remove things Strap installs (so we can test installing them from scratch).
before_script:
  - sudo rm -rf /usr/local/* /usr/local/.??* /Applications/Xcode.app /Library/Developer/CommandLineTools /opt/homebrew-cask/Caskroom
  - sudo pkgutil --forget com.apple.pkg.CLTools_Executables

# Install Strap and then test installing packages works.
script:
  - ./script/cibuild
