#!/bin/bash
set -e

# Load helpers
for helper in $TILLAGE_REPO/helpers/*; do
  if [ -f "$helper" ] ; then
    #shellcheck disable=1090
    . $helper
  fi
done

# Update enviroment scripts
render $TILLAGE_REPO/templates/env.sh > $TILLAGE_HOME/env.sh
render $TILLAGE_REPO/templates/env.fish > $TILLAGE_HOME/env.fish

# Include modules
include_module "modules/ruby"
include_module "modules/node"
include_module "modules/platanus"

include_module "people/$TILLAGE_GITHUB_USER"
