#!/bin/bash
set -e
cd "$(dirname "$0")/.."

cleanup() {
  if [ -n "$SERVER_PID" ]; then
    kill "$SERVER_PID"
  fi
}

trap "cleanup" EXIT

script/bootstrap
bundle exec foreman check
script/server &
SERVER_PID="$!"
sleep 5
curl -O http://localhost:5000/install
kill "$SERVER_PID"
wait "$SERVER_PID" || true
SERVER_PID=

export STRAP_CI=1
export TILLAGE_CI=1
bash install --debug

# shellcheck disable=1091
source /opt/tillage/env.sh
[ -n "$TILLAGE_HOME" ]
