#!/usr/bin/env bash
# Usage: tillage render-template <template-path>
# Help: Render a file to STDOUT using the current environment
set -e
[ -n "$TILLAGE_DEBUG" ] && set -x

render-template() {
    declare file="$1"
    declare data=$(< "$file")
    declare delimiter="__apply_shell_expansion_delimiter__"
    declare command="cat <<$delimiter"$'\n'"$data"$'\n'"$delimiter"
    eval "$command"
}

command="$1"
case "$command" in
"")
  tillage-help render-template >&2
  exit 1;
  ;;
*)
  render-template "$1"
  ;;
esac
