#!/usr/bin/env bash
set -e

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

libexec_path="$(abs_dirname "$0")"
export _TILLAGE_ROOT="$(abs_dirname "$libexec_path")"
export _TILLAGE_HOME="$(abs_dirname "$_TILLAGE_ROOT")"
export _TILLAGE_MODULES=$_TILLAGE_ROOT/modules
export _TILLAGE_ENV_D=$_TILLAGE_HOME/env.d

export PATH="${libexec_path}:$PATH"

# Parse arguments
ARGS=("$@")
for i in "${!ARGS[@]}"; do
  arg="${ARGS[$i]}"
  if [ "$arg" = "--debug" ]; then
    export TILLAGE_DEBUG="1"
    set -x
    unset ARGS[$i]
  fi
done

command="$1"
case "$command" in
"" | "-h" | "--help" )
  exec tillage-help
  ;;
* )
  command_path="$(command -v "tillage-$command" || true)"
  if [ ! -x "$command_path" ]; then
    echo "tillage: no such command \`$command'" >&2
    exit 1
  fi

  shift
  exec "$command_path" "$@"
  ;;
esac
