#!/bin/bash

# Automatically generated by Tillage. Don't edit directly. This file
# sets up paths and basic environment for the Tillage dev environment,
# and is intended to be sourced in your shell profile.

set +e
set +u

# Make the root of Tillage available.
export TILLAGE_HOME=$TILLAGE_HOME

# Make the github username available
export TILLAGE_GITHUB_USER=$STRAP_GITHUB_USER

# Source any module specific env file
for env_file in \$TILLAGE_HOME/env.d/*.sh ; do
  if [ -f \$env_file ] ; then
    . \$env_file
  fi
done

# Tillage is active.
if [ -d "\$TILLAGE_HOME/repo/.git" ]; then
  export TILLAGE_SETUP_VERSION=\`GIT_DIR=\$TILLAGE_HOME/repo/.git git rev-parse --short HEAD\`
else
  echo "Tillage could not load properly!"
fi
