#!/bin/sh

set -e
cd "$(dirname "$0")/.."

find . -name "*.sh" -type f | while read -r line; do
  shellcheck -x "$line"
done

for helper in helpers/* ; do
  if [ -f "$helper" ] ; then
    shellcheck -x "$helper"
  fi
done
